### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by hanselsen** [IvanSanchez/Leaflet.ImageOverlay.Rotated#18]
I would like to know if this library is still being maintained. The last commit was some while ago.
If not, what would be a nice alternative?

**Comment by IvanSanchez** [comment]
This is a weird question, man. If there's no rush of bugs, and no weird new use cases to be covered, there's no need to spend time nor resources on maintenance.

I'm gonna point you towards [the secret life of open source developers](https://www.youtube.com/watch?v=Q187JGeXueA), since something tells me you need to watch it.

**Comment by hanselsen** [comment]
Sorry to have pushed your buttons with my question. I wish you a great weekend.
