### ISSUE TITLE
Compute points from top left and bottom right

### ISSUE THREAD

**Issue by skol-pro** [IvanSanchez/Leaflet.ImageOverlay.Rotated#6]
I have:

- a top left and a bottom right position
- dimensions of the image

How could I get the `topright` and `bottomleft` ?

**Comment by IvanSanchez** [comment]
You can't, because the earth is round, [spherical trigonometry](https://en.wikipedia.org/wiki/Spherical_trigonometry) is hard, which means that the angles of a triangle can add up to more than 180°, which means that the angles of a cuadrilateral can add up to more than 360°, which means there is no reliable way of calculating the third point given two corner points and the side lengths because you cannot guarantee that the angles are 90°.

Project your corner coordinates into a map projection that adds minimal distortion to the image, perform 2D trigonometry there, get the third point.
